[project]
name = "mlops-lab-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vitorio", email = "kassisvito@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
mlops-lab-1 = "mlops_lab_1:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "dvc>=3.67.1",
]
